spring:
  application:
    name: zmessages
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

server:
  port: 8087
  servlet:
    context-path: /${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: default

app:
  mailer: zoho
  smtp:
    gmail:
      host: smtp.gmail.com
      port: 587
      username: ${GMAIL_USERNAME}
      password: ${GMAIL_PASSWORD}
    zoho:
      host: smtp.zeptomail.in
      port: 587
      username: ${ZOHOMAIL_USERNAME}
      password: ${ZOHOMAIL_PASSWORD}
    debug: true

