spring:
  application:
    name: zmessages
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

server:
  port: 8087
  servlet:
    context-path: /${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: default

app:
  mailer: zoho
  smtp:
    gmail:
      host: smtp.gmail.com
      port: 587
      username: ${GMAIL_USERNAME:'default'}
      password: ${GMAIL_PASSWORD:'default'}
    zoho:
      host: smtp.zeptomail.in
      port: 587
      username: ${ZOHOMAIL_USERNAME:'default'}
      password: ${ZOHOMAIL_PASSWORD:'default'}
    debug: true
  smser: plivo
  sms:
    plivo:
        auth-id: ${PLIVO_AUTH_ID:'default'}
        auth-token: ${PLIVO_AUTH_TOKEN:'default'}



