spring:
  application:
    name: zfiles
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

server:
  port: 8086
  servlet:
    context-path: /${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: default

zfiles:
  cdn-type: local

local:
  prefix-http-url: http://localhost
  prefix-upload: /Users/madan/Documents/JayaMeen/www/files

gcp:
  prefix-http-url: https://storage.googleapis.com
  prefix-upload:
  project-id: ${GCP_PROJECT_ID:test}
  bucket-id: ${GCP_BUCKET_ID:test}
  upload-url: https://storage.googleapis.com
  config-data: ${GCP_CONFIG_DATA_KEY:''}

#digital ocean-s3
#s3:
  #prefix-http-url: https://uxin.sgp1.digitaloceanspaces.com
  #prefix-upload:
  #region: sgp1
  #bucket-id: uxin
  #upload-url: https://sgp1.digitaloceanspaces.com
  #key: ${DO_KEY:test}
  #secret: ${DO_SECRET:test}

s3:
  prefix-http-url: https://xindus.s3.ap-south-1.amazonaws.com
  prefix-upload:
  region: ap-south-1
  bucket-id: xindus
  upload-url: https://s3.ap-south-1.amazonaws.com
  key: ${AWSS3_KEY:test}
  secret: ${AWSS3_SECRET:test}

azure:
  connection-string: ${AZURE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=teststorage;AccountKey=yourkey;EndpointSuffix=core.windows.net}
  endpoint: ${AZURE_ENDPOINT:https://teststorage.blob.core.windows.net/}
  container-name: ${AZURE_CONTAINER_NAME:test}
  prefix-http-url: https://xindusazureblobstorage.blob.core.windows.net
  prefix-upload: